data:
  splits:
    raman_col_len: 2048
    absorption_col_len: 811
  raw:
    trn_path: 'data/raw/hm_trn.csv'
    vld_path: 'data/raw/hm_tst.csv'
  interim:
    raman:
      XX_path: 'data/interim/corr_raman_XX.feather'
      Xy_path: 'data/interim/corr_raman_Xy.feather'
    absorption:
      XX_path: 'data/interim/corr_absorption_XX.feather'
      Xy_path: 'data/interim/corr_absorption_Xy.feather'
  processed:
    trn:
      X:
        raman_path: 'data/processed/X_trn_raman.feather'
        absorption_path: 'data/processed/X_trn_absorption.feather'
      y_ions_path: 'data/processed/y_trn_ions.feather'
    vld:
      X:
        raman_path: 'data/processed/X_vld_raman.feather'
        absorption_path: 'data/processed/X_vld_absorption.feather'
      y_ions_path: 'data/processed/y_vld_ions.feather'

feature_selection:
  fcbf:
    level_XX: 0.99
    level_Xy: 0.1