data:
  splits:
    raman_col_len: 2048
    absorption_col_len: 811
  raw:
    trn_path: 'data/raw/hm_trn.csv'
    vld_path: 'data/raw/hm_tst.csv'
  processed:
    trn:
      X_raman_path: 'data/processed/X_trn_raman.feather'
      X_absorption_path: 'data/processed/X_trn_absorption.feather'
      y_ions_path: 'data/processed/y_trn_ions.feather'
    vld:
      X_raman_path: 'data/processed/X_vld_raman.feather'
      X_absorption_path: 'data/processed/X_vld_absorption.feather'
      y_ions_path: 'data/processed/y_vld_ions.feather'