data:
  splits:
    raman_col_len: 2048
    absorption_col_len: 811
  raw:
    trn_path: 'data/raw/hm_trn.csv'
    vld_path: 'data/raw/hm_tst.csv'
    tst_path: 'data/raw/hm_pro.csv'
  interim:
    raman:
      XX_path: 'data/interim/corr/raman_XX.feather'
      Xy_path: 'data/interim/corr/raman_Xy.feather'
      masks:
        fcbf_path: 'data/interim/masks/fcbf_raman.feather'
    absorption:
      XX_path: 'data/interim/corr/absorption_XX.feather'
      Xy_path: 'data/interim/corr/absorption_Xy.feather'
      masks:
        fcbf_path: 'data/interim/masks/fcbf_absorption.feather'
  processed:
    trn:
      X:
        raman_path: 'data/processed/X_trn_raman.feather'
        absorption_path: 'data/processed/X_trn_absorption.feather'
      y_ions_path: 'data/processed/y_trn_ions.feather'
    vld:
      X:
        raman_path: 'data/processed/X_vld_raman.feather'
        absorption_path: 'data/processed/X_vld_absorption.feather'
      y_ions_path: 'data/processed/y_vld_ions.feather'
    tst:
      X:
        raman_path: 'data/processed/X_tst_raman.feather'
        absorption_path: 'data/processed/X_tst_absorption.feather'
      y_ions_path: 'data/processed/y_tst_ions.feather'

feature_selection:
  fcbf:
    level_XX: 0.95
    level_Xy: 0.00

model_params:
  lr: 0.01
  epochs: 1000
  batch_size: 8
  patience: 500
  min_delta: 0

output:
  models:
    raman_full_model: 'models/raman_full_model.keras'
    raman_fcbf_model: 'models/raman_fcbf_model.keras'
    absorption_full_model: 'models/absorption_full_model.keras'
    absorption_fcbf_model: 'models/absorption_fcbf_model.keras'
    both_full_model_path: 'models/both_full_model_path.keras'
    both_fcbf_model_path: 'models/both_fcbf_model_path.keras'